import { NextResponse } from "next/server";

import { verifySignature } from "@/lib/crypto";
import { StrictSchemaValidator } from "@/lib/ai/validator";
import { ProcessingOrchestrator } from "@/lib/processing-orchestrator";
import { AIModelType, PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();


export async function POST(req: Request) {
  try {
    const signature = req.headers.get("x-internal-signature");
    const textBody = await req.text();

    // 1. Asynchronous Webhook Security (Cryptographic Signatures)
    if (!signature || !verifySignature(textBody, signature)) {
      console.warn("[Job Process Webhook]: Unauthorized access attempt.");
      return NextResponse.json({ error: "Unauthorized access" }, { status: 401 });
    }

    const body = JSON.parse(textBody);
    const { jobId } = body;

    const job = await prisma.agentJob.findUnique({
      where: { id: jobId },
      include: { user: true }
    });

    if (!job || job.status !== "QUEUED") {
      return NextResponse.json({ error: "Job not found or not in QUEUED state" }, { status: 400 });
    }

    // Mark Job as PROCESSING
    await prisma.agentJob.update({
      where: { id: jobId },
      data: { status: "PROCESSING", progress: 10 }
    });

    const payload: any = job.payload;
    const config = await prisma.systemConfig.findUnique({ where: { id: "CURRENT_GLOBAL_CONFIG" } });

    // Dynamic Model Routing
    const modelName = config?.active_ai_provider === 'OPENROUTER' ? config?.openrouter_model_name : config?.direct_model_name;
    const modelEnum = AIModelType.GEMINI_35_FLASH; // Fallback

    await prisma.agentJob.update({
      where: { id: jobId },
      data: { progress: 30 }
    });

    // Simulated Master Model Blueprint Generation
    const masterJsonBlueprint = JSON.stringify({
      platforms: payload.platforms || ["twitter"],
      tone: payload.tone || "professional",
      length: payload.length || "medium",
      globalContextAnchor: "Generated by Master Node",
      highRisk: (payload.platforms && payload.platforms.length > 5) ? true : false
    });

    // 2. Strict Schema Validator (Anti-Hallucination Layer)
    let validatedPlan;
    try {
      validatedPlan = StrictSchemaValidator.validatePlan(masterJsonBlueprint);
    } catch (validationError: any) {
      await prisma.agentJob.update({
        where: { id: jobId },
        data: { status: "FAILED", result: { error: validationError.message } }
      });
      return NextResponse.json({ error: validationError.message }, { status: 400 });
    }

    // 3. The "Kastra" Guardrails (Human-In-The-Loop)
    if (validatedPlan.highRisk) {
      await prisma.agentJob.update({
        where: { id: jobId },
        data: {
          status: "FAILED",
          result: {
            error: "Kastra Guardrail Intercept: High-risk action detected. Human authorization required.",
            action: "TRIGGER_KASTRA_APPROVAL"
          }
        }
      });
      return NextResponse.json({ error: "Action requires authorization" }, { status: 403 });
    }

    await prisma.agentJob.update({
      where: { id: jobId },
      data: { progress: 60 }
    });

    // Execute the Worker Processing loop using the validated plan
    const orchestratorResult = await ProcessingOrchestrator.orchestrate(
      {
        userId: job.user.id,
        tier: job.user.tier,
        inputText: payload.inputText || "",
        fileBase64: payload.fileBase64 || null,
        fileMimeType: payload.fileMimeType || null,
        platforms: validatedPlan.platforms,
        tone: validatedPlan.tone || "professional",
        length: validatedPlan.length || "medium",
        flashMode: payload.flashMode || false,
        searchDepth: payload.searchDepth || "basic",
        maxSearchResults: payload.maxSearchResults || 0,
        orchestrationMode: payload.orchestrationMode || "auto",
      },
      modelName || "google/gemini-3.5-flash"
    );

    await prisma.agentJob.update({
      where: { id: jobId },
      data: { progress: 90 }
    });

    // Mark as COMPLETED and save results
    await prisma.agentJob.update({
      where: { id: jobId },
      data: {
        status: "COMPLETED",
        progress: 100,
        result: orchestratorResult as any,
        completedAt: new Date()
      }
    });

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("[Job Process Error]:", error);

    // Try to update job to FAILED
    try {
      const textBody = await req.clone().text();
      const body = JSON.parse(textBody);
      if (body.jobId) {
        await prisma.agentJob.update({
          where: { id: body.jobId },
          data: { status: "FAILED", result: { error: error.message } }
        });
      }
    } catch (e) {
      // Ignore
    }

    return NextResponse.json({ error: "Processing Failed" }, { status: 500 });
  }
}
